# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]
    
permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: npm install, build, and test
      run: |
        npm install doctest
        npm install standard --save-dev
        npx doctest **/*.js || true #TODO: Add all doctest
        npm ci
        npm run build --if-present
      env:
        CI: true
        
    - name: SonarCloud Scan # Action For ensuring the code quality
      if: contains(fromJson('pull_request_target'), github.event_name)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.pullrequest.key=${{github.event.number}}
            -Dsonar.pullrequest.github.repository=williamson922/outils
            -Dsonar.pullrequest.provider = GitHub
            -Dsonar.pullrequest.base=master
            -Dsonar.projectKey=williamson922_outils
            -Dsonar.organization=williamson922
            
    - name: SonarCloud Scan # Action For ensuring the code quality
      if: contains(fromJson('push'), github.event_name)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.projectKey=williamson922_outils
            -Dsonar.organization=williamson922
            
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: ${{secrets.DOCKER_USERNAME}}/outils
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Run tests and collect coverage
      run: npm run test -- --coverage
      
    - name: Code Coverage
      uses: codecov/codecov-action@v3.1.0 # actions for checking coverage of test code
    
        
    
